stages:
  train:
    cmd: python train1.py
    deps:
      - train1.py
      - data.csv
    outs:
      - model.pkl
    metrics:
      - metrics.json
    params:
      - train.fit_intercept
      - train.test_size
      - train.random_state

